server:
  port: 8081
spring:
  application:
    name: Learn-Management-Service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: 'classpath:/db/changelog/liquibase.change-log.xml'
    database-change-log-lock-table: learn-lock
    database-change-log-table: learn-changelog
  sql:
    init:
      platform: postgres


logging:
  level:
    org.springframework.security: DEBUG


